import { ReportCategory } from '@prisma/client';

export type SeedReport = {
  category: ReportCategory;
  severity: number;
  title: string;
  body: string;
  nickname: string;
  votes: number;
  daysAgo: number;
};

export type SeedRestaurant = {
  name: string;
  city: string;
  district: string;
  addressHint: string;
  cuisine: string;
  daysAgo: number;
  reports: SeedReport[];
};

export const SEED_RESTAURANTS: SeedRestaurant[] = [
  {
    name: 'Eminönü Balık Pusulası',
    city: 'İstanbul',
    district: 'Fatih',
    addressHint: 'Eminönü sahil',
    cuisine: 'Balık',
    daysAgo: 40,
    reports: [
      {
        category: ReportCategory.FOOD_POISONING,
        severity: 5,
        title: 'Sabaha kadar mide',
        body: 'Üç kişilik masada levrek dedikleri tabağı paylaştık. Gece üçümüz de aynı şikayetle uyandık. Doktor şüpheli gıda dedi, laboratuvar sonucu yok; yine de bir daha o iskeleye inmem.',
        nickname: 'iskele pişmanı',
        votes: 4,
        daysAgo: 6,
      },
      {
        category: ReportCategory.HYGIENE,
        severity: 5,
        title: 'Tezgahın hali iç açıcı değil',
        body: 'Balık tezgahının yanında sinek turu vardı, bıçaklar aynı bezle silindi. Tuvalet kapısı mutfak geçidine açılıyor, sabunluk boştu.',
        nickname: 'burnu kalkan',
        votes: 3,
        daysAgo: 12,
      },
      {
        category: ReportCategory.HYGIENE,
        severity: 4,
        title: 'Buzlu su bardağı lekeli geldi',
        body: 'Su bardağının kenarında ruj değil, kurumuş bir leke vardı. Değiştir dedik, ikincisi de aynı tepside geldi.',
        nickname: 'bardak denetçisi',
        votes: 2,
        daysAgo: 18,
      },
      {
        category: ReportCategory.WRONG_OR_COLD,
        severity: 4,
        title: 'Izgara değil, buzdolabı',
        body: 'Balık ortasından soğuktu, dışına sos sürülmüş. Garson bugün böyle deyip masadan ayrıldı.',
        nickname: 'soğuk tabak',
        votes: 1,
        daysAgo: 3,
      },
    ],
  },
  {
    name: 'Beyoğlu Döner & Co.',
    city: 'İstanbul',
    district: 'Beyoğlu',
    addressHint: 'İstiklal çevresi',
    cuisine: 'Döner',
    daysAgo: 30,
    reports: [
      {
        category: ReportCategory.SCAM_PRICING,
        severity: 5,
        title: 'Ekmek arası, hesap ziyafet',
        body: 'Vitrindeki fiyatla hesap uyuşmadı. İçecek küçük şişe, fişte büyük boy yazıyordu. İtiraz edince kasa fişi yavaşça katladı.',
        nickname: 'hesap mahkumu',
        votes: 2,
        daysAgo: 4,
      },
      {
        category: ReportCategory.SCAM_PRICING,
        severity: 4,
        title: 'Servis ücreti menüde yoktu',
        body: 'İki dürüm, iki ayran. Sonra yüzde on servis ve bir de teras farkı çıktı. Teras, üç tabureden ibaretti.',
        nickname: 'fiş okuyan',
        votes: 1,
        daysAgo: 9,
      },
      {
        category: ReportCategory.RUDE_SERVICE,
        severity: 4,
        title: 'Soru sorunca ses yükseldi',
        body: 'Etin içi kuruydu, nazikçe sordum. Karşılık olarak herkesin duyacağı tonda müşteri seçiyoruz dendi. Tartışmadım, çıktım.',
        nickname: 'sessiz çıkan',
        votes: 1,
        daysAgo: 15,
      },
      {
        category: ReportCategory.FALSE_ADS,
        severity: 3,
        title: 'Odun ateşi posterden ibaret',
        body: 'Camda odun ateşi, taş fırın, yüzde yüz dana yazıyor. İçeride düz elektrikli ızgara ve etin ne olduğu belli değil. Fotoğraftaki porsiyon da masadakinin iki katı.',
        nickname: 'poster avcısı',
        votes: 0,
        daysAgo: 21,
      },
    ],
  },
  {
    name: 'Kadıköy Midye Tezgahı',
    city: 'İstanbul',
    district: 'Kadıköy',
    addressHint: 'Moda iskelesi',
    cuisine: 'Sokak lezzeti',
    daysAgo: 28,
    reports: [
      {
        category: ReportCategory.HYGIENE,
        severity: 5,
        title: 'Midye dolması güneşte bekliyor',
        body: 'Tezgah öğlen güneşinde, buz kalmamış. Limonlar aynı elde hem para üstü hem dolma için kullanılıyor.',
        nickname: 'midye pişmanı',
        votes: 2,
        daysAgo: 2,
      },
      {
        category: ReportCategory.FOOD_POISONING,
        severity: 4,
        title: 'Akşamüstü midye, gece şüphe',
        body: 'Altı midye yedim, gece mide krampları başladı. Başka bir şey yememiştim. Kesin teşhis konmadı ama tezgahla aynı saat çakışıyor.',
        nickname: 'kramp',
        votes: 3,
        daysAgo: 8,
      },
      {
        category: ReportCategory.WRONG_OR_COLD,
        severity: 4,
        title: 'İçinden pilav değil, buz çıktı',
        body: 'İki tanesini açtım, içi soğuktu ve pirinç topak topak. Tazesi bu deyip yenisini de aynı kovadan aldılar.',
        nickname: 'açan kişi',
        votes: 1,
        daysAgo: 14,
      },
    ],
  },
  {
    name: 'Girne Manzara Teras',
    city: 'Girne',
    district: 'Girne',
    addressHint: 'Bellapais yolu',
    cuisine: 'Kafe',
    daysAgo: 22,
    reports: [
      {
        category: ReportCategory.FALSE_ADS,
        severity: 5,
        title: 'Manzara fotoğrafta kalmış',
        body: 'İlan dağ ve deniz vadediyor. Masa bir duvarın dibinde, manzara komşu inşaatın brandası. Porsiyon da küçük tabak içinde sos.',
        nickname: 'teras hayaleti',
        votes: 3,
        daysAgo: 5,
      },
      {
        category: ReportCategory.SCAM_PRICING,
        severity: 5,
        title: 'Çay fiyatı tur fiyatı',
        body: 'İki çay, bir tost. Hesap, İstanbul havaalanı kafesiyle yarışıyor. Menüde küçük puntoyla yabancı fiyatı, yerli fiyatı yok.',
        nickname: 'fiş şoku',
        votes: 2,
        daysAgo: 11,
      },
      {
        category: ReportCategory.RUDE_SERVICE,
        severity: 4,
        title: 'Sormadan bahşiş eklendi',
        body: 'Bahşiş kalemini çizmemi istedim. Garson gözünü devirip hesabı masaya bıraktı, bir daha uğramadı. Kimseyle tartışmadım.',
        nickname: 'kalem çizen',
        votes: 2,
        daysAgo: 16,
      },
    ],
  },
  {
    name: 'Gazimağusa Sahil Izgara',
    city: 'Gazimağusa',
    district: 'Maraş',
    addressHint: 'sahil yürüyüşü',
    cuisine: 'Izgara',
    daysAgo: 26,
    reports: [
      {
        category: ReportCategory.FOOD_POISONING,
        severity: 5,
        title: 'Tavuk şişten sonra şüphe',
        body: 'Akşam tavuk şiş yedik, gece iki kişide aynı mide bulantısı. Başka mekan yoktu o gün. Resmi kayıt tutturmadık, sadece uyarı olsun.',
        nickname: 'şiş mağduru',
        votes: 2,
        daysAgo: 7,
      },
      {
        category: ReportCategory.HYGIENE,
        severity: 4,
        title: 'Izgara telinde dünden kalan',
        body: 'Telin üstünde yanık artıklar vardı, yeni eti doğrudan üzerine koydular. Peçetelik boş, masa yapış yapıştı.',
        nickname: 'tel bakan',
        votes: 1,
        daysAgo: 13,
      },
      {
        category: ReportCategory.RUDE_SERVICE,
        severity: 3,
        title: 'Porsiyon diye alay edildi',
        body: 'Et incecikti, kibarca sordum. Cevap: beğenmiyorsan git evde ye. Ses yükseltmedim, hesabı ödeyip çıktım.',
        nickname: 'kısa kalan',
        votes: 0,
        daysAgo: 19,
      },
    ],
  },
  {
    name: 'Lefkoşa Kebap Sarayı',
    city: 'Lefkoşa',
    district: 'Lefkoşa',
    addressHint: 'Dereboyu',
    cuisine: 'Kebap',
    daysAgo: 18,
    reports: [
      {
        category: ReportCategory.RUDE_SERVICE,
        severity: 5,
        title: 'Çocuklu masaya bağırıldı',
        body: 'Çocuk sandalyesi istedik, yok dediler. Sonra yüksek sesle burası aile yeri değil dendi. Mekan kalabalıktı, biz de sessizce kalktık.',
        nickname: 'erken kalkan',
        votes: 1,
        daysAgo: 3,
      },
      {
        category: ReportCategory.HYGIENE,
        severity: 4,
        title: 'Lavaş yere düştü, yine geldi',
        body: 'Lavaş servis sırasında yere düştü. Aynı lavaş, silkelenip tabağa kondu. İtiraz edince yenisi gelmedi, hesabı da düşmediler.',
        nickname: 'lavaş gören',
        votes: 1,
        daysAgo: 10,
      },
      {
        category: ReportCategory.SCAM_PRICING,
        severity: 3,
        title: 'Acılı ezme ayrıca yazılmış',
        body: 'Menüde kebap yanına ezme dahil görünüyor. Fişte ezme ayrı kalem. Fark küçük ama üç masada da aynı oyun var gibiydi.',
        nickname: 'ezme muhasebesi',
        votes: 0,
        daysAgo: 17,
      },
    ],
  },
  {
    name: 'Şişli Gece Pizzası',
    city: 'İstanbul',
    district: 'Şişli',
    addressHint: 'Osmanbey',
    cuisine: 'Pizza',
    daysAgo: 16,
    reports: [
      {
        category: ReportCategory.WRONG_OR_COLD,
        severity: 5,
        title: 'Margarita buz gibi geldi',
        body: 'Kırk dakika sonra kutu soğuktu, peynir donmuş gibi. Isıtın deyince mikrodalgaya atıp geri getirdiler, hamur lastik oldu.',
        nickname: 'soğuk pizza',
        votes: 1,
        daysAgo: 1,
      },
      {
        category: ReportCategory.WRONG_OR_COLD,
        severity: 4,
        title: 'Karışık istedim, sade geldi',
        body: 'Sipariş notuna mantar ve zeytin yazdım. Gelen pizzada ikisi de yok, bunun yerine sucuk var. Değişim yok, iade de yok dendi.',
        nickname: 'not düşen',
        votes: 1,
        daysAgo: 9,
      },
      {
        category: ReportCategory.FALSE_ADS,
        severity: 3,
        title: 'Odun fırın iddiası elektrikli',
        body: 'Uygulamada odun fırını, İtalyan hamur yazıyor. İçeride konveyör bant gördüm. Hamur da karton gibiydi.',
        nickname: 'fırın meraklısı',
        votes: 0,
        daysAgo: 20,
      },
    ],
  },
  {
    name: 'Fatih Tantuni Durağı',
    city: 'İstanbul',
    district: 'Fatih',
    addressHint: 'Aksaray çevresi',
    cuisine: 'Tantuni',
    daysAgo: 14,
    reports: [
      {
        category: ReportCategory.SCAM_PRICING,
        severity: 4,
        title: 'Duble deyip tek koydular',
        body: 'Duble et istedim, lavaşın içi eskisi kadar boştu. Fiyat duble. Tartışınca bu bizim duble standardı denip konu kapatıldı.',
        nickname: 'lavaş içi',
        votes: 1,
        daysAgo: 4,
      },
      {
        category: ReportCategory.WRONG_OR_COLD,
        severity: 4,
        title: 'Et soğuk, baharat sıcak',
        body: 'Tantuni yağı soğumuş, sadece pul biber acı olduğu için sıcak sanıyorsun. İkinci lokmada fark ettik.',
        nickname: 'ikinci lokma',
        votes: 0,
        daysAgo: 11,
      },
      {
        category: ReportCategory.RUDE_SERVICE,
        severity: 3,
        title: 'Sıra beklerken itilmek',
        body: 'Tezgahta sıra vardı. Yeni gelen birine önce verildi, bana da karışma dendi. Bağırmadım, siparişi iptal ettim.',
        nickname: 'sıradan çıkan',
        votes: 0,
        daysAgo: 15,
      },
    ],
  },
  {
    name: 'Beşiktaş Kahve Tiyatrosu',
    city: 'İstanbul',
    district: 'Beşiktaş',
    addressHint: 'çarşı içi',
    cuisine: 'Kafe',
    daysAgo: 12,
    reports: [
      {
        category: ReportCategory.FALSE_ADS,
        severity: 4,
        title: 'Filtre kahve, termos suyu',
        body: 'Üçüncü dalga filtre diye satılan şey termosun dibindeki suya benziyordu. Çekirdek tabelada Etiyopya, fincanda iz yok.',
        nickname: 'fincan bakan',
        votes: 1,
        daysAgo: 6,
      },
      {
        category: ReportCategory.RUDE_SERVICE,
        severity: 4,
        title: 'Laptop kapağını kapattırdılar',
        body: 'Tek kişilik masada sessizce oturuyordum. Görevli kapağı kapat, burası ofis değil diye bağırdı. Başka kimse rahatsız olmamıştı.',
        nickname: 'kapak kapatan',
        votes: 0,
        daysAgo: 8,
      },
      {
        category: ReportCategory.SCAM_PRICING,
        severity: 2,
        title: 'Küçük boy, büyük fiyat',
        body: 'Sütlü kahve fiyatı yandaki iki dükkanın üstünde, bardak ise yarı yarıya. Lezzet kötü değildi, hesap kırıcıydı.',
        nickname: 'bardak ölçen',
        votes: 0,
        daysAgo: 13,
      },
    ],
  },
  {
    name: 'Kadıköy Organik Masal',
    city: 'İstanbul',
    district: 'Kadıköy',
    addressHint: 'Moda',
    cuisine: 'Kafe',
    daysAgo: 11,
    reports: [
      {
        category: ReportCategory.FALSE_ADS,
        severity: 5,
        title: 'Organik yazısı, market kavanozu',
        body: 'Menüde her şey organik, köy yumurtası, taş değirmen. Mutfak kapısı aralıktı, tezgahta market reçel kavanozu ve toptan ketçap duruyordu.',
        nickname: 'etiket okuyan',
        votes: 2,
        daysAgo: 2,
      },
      {
        category: ReportCategory.SCAM_PRICING,
        severity: 4,
        title: 'Tost fiyatına küçük bir tiyatro',
        body: 'Kaşarlı tost, ev yapımı limonata. Hesap iki kişilik dışarı yemeği kadar. Limonata da şurup tadındaydı, ev yapımı iddiası havada kaldı.',
        nickname: 'şurup fark eden',
        votes: 1,
        daysAgo: 9,
      },
    ],
  },
  {
    name: 'İskele Pide Ocağı',
    city: 'İskele',
    district: 'İskele',
    addressHint: 'merkez',
    cuisine: 'Pide',
    daysAgo: 9,
    reports: [
      {
        category: ReportCategory.HYGIENE,
        severity: 3,
        title: 'Tepsi yağlı, peçete yok',
        body: 'Pide lezzetli sayılırdı ama tepsi bir önceki müşteriden yağlı geldi. Peçete isteyince mutfaktan kağıt havlu yırtıp verdiler.',
        nickname: 'peçetesiz',
        votes: 1,
        daysAgo: 5,
      },
      {
        category: ReportCategory.WRONG_OR_COLD,
        severity: 3,
        title: 'Kıymalı istedim, kaşarlı geldi',
        body: 'Fırından çıkan pide kaşarlıydı. Değiştirdiler, ikincisi ılık ve hamur yer yer çiğdi. Kötü niyet görmedim, özensizlik gördüm.',
        nickname: 'ılık pide',
        votes: 0,
        daysAgo: 8,
      },
    ],
  },
  {
    name: 'Girne Liman Börekçisi',
    city: 'Girne',
    district: 'Girne',
    addressHint: 'liman',
    cuisine: 'Börek',
    daysAgo: 7,
    reports: [
      {
        category: ReportCategory.HYGIENE,
        severity: 2,
        title: 'Vitrin camı puslu',
        body: 'Börek fena değildi. Vitrin camı yağlı ve pusluydu, maşa tezgahta açıkta duruyordu. Büyük skandal değil, özensiz bir vitrin.',
        nickname: 'cam silen değil',
        votes: 0,
        daysAgo: 3,
      },
      {
        category: ReportCategory.WRONG_OR_COLD,
        severity: 2,
        title: 'Su böreği ılık çıktı',
        body: 'Öğleden sonra su böreği ılıktı, çıtır değil. Isıtabiliriz dediler, bekledim, biraz düzeldi. Fiyatı da abartılı değildi.',
        nickname: 'ılık börek',
        votes: 0,
        daysAgo: 6,
      },
    ],
  },
];
